services:
  uvdesk_db:
    image: mysql:5.7
    container_name: uvdesk_db
    ports:
      - "3306:3306"
    volumes:
      - ./data/uvdeskdb:/var/lib/mysql
      - ./conf:/etc/uvdesk/conf:rw
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - cpt_docker_internal

  uvdesk_app:
    image: webkul/uvdesk
    container_name: uvdesk_app
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_HOST: uvdesk_db
    networks:
      - cpt_docker_internal
    volumes:
      - uvdesk_config:/var/www/uvdesk/config
      - uvdesk_db:/var/lib/mysql
    ports:
      - "8080:80"


volumes:
  uvdesk_config:
  uvdesk_db:

networks:
  cpt_docker_internal:
    external: true